[project]
name = "imap-sorting-hat"
version = "0.0.5"
requires-python = ">=3.13"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]